name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
on: push

jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install flit
      run: >-
        python -m
        pip install
        flit
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        flit build
